# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run crawler

# Every 4 hours
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'crusher-dev/web-history'

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.5.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install node modules
      run: pnpm install
    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: Install azure cli
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    - name: Login to azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p=${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    
    - name: Build worker & start
      run: cd packages/backend && pnpm build:worker && pnpm worker
      env:
        BACKBLAZE_APPLICATION_KEY_ID: ${{ secrets.BACKBLAZE_APPLICATION_KEY_ID }}
        BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}
        BACKBLAZE_BUCKET: ${{ secrets.BACKBLAZE_BUCKET }}
        BACKBLAZE_BUCKET_NAME: ${{ secrets.BACKBLAZE_BUCKET_NAME }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        AZURE_ACCOUNT_NAME: crusher
        AZURE_STORAGE_CONTAINER_NAME: web-history